# Generated by Django 5.2.7 on 2025-12-15 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0004_alter_branch_sucurestado'),
        ('clients', '0005_alter_cliente_sucurcod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('receCod', models.AutoField(primary_key=True, serialize=False)),
                ('receFech', models.DateField(verbose_name='Fecha')),
                ('receEsfeD', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Esfera OD')),
                ('receCilinD', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cilindro OD')),
                ('receEjeD', models.IntegerField(verbose_name='Eje OD')),
                ('receEsfel', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Esfera OI')),
                ('receCilinl', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Cilindro OI')),
                ('receEjel', models.IntegerField(verbose_name='Eje OI')),
                ('receDistPupilar', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='DP')),
                ('receTipoLent', models.CharField(max_length=100, verbose_name='Tipo Lente')),
                ('receObserva', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('receRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Registro')),
                ('receEstado', models.CharField(default='Activo', max_length=50)),
                ('cliCod', models.ForeignKey(db_column='cliCod', on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='clients.cliente', verbose_name='Paciente')),
                ('sucurCod', models.ForeignKey(blank=True, db_column='sucurCod', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='Branch.branch', verbose_name='Sucursal')),
                ('usuCod', models.ForeignKey(db_column='usuCod', limit_choices_to={'roles__rolNom': 'OPTOMETRA'}, on_delete=django.db.models.deletion.PROTECT, related_name='recetas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Optómetra')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
    ]
