# Generated by Django 5.2.7 on 2025-11-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('rolCod', models.AutoField(primary_key=True, serialize=False)),
                ('rolNom', models.CharField(choices=[('CAJERO', 'Cajero'), ('VENDEDOR', 'Vendedor'), ('OPTOMETRA', 'Optometra'), ('SUPERVISOR', 'Supervisor'), ('LOGISTICA', 'Logística')], max_length=50)),
                ('rolDes', models.CharField(max_length=50)),
                ('rolEstado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('rolNivel', models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('usuCod', models.AutoField(primary_key=True, serialize=False)),
                ('usuNom', models.CharField(max_length=20, unique=True)),
                ('usuContra', models.CharField(max_length=128)),
                ('usuApell', models.CharField(max_length=20)),
                ('usuDNI', models.CharField(max_length=8)),
                ('usuTel', models.CharField(max_length=9)),
                ('usuEmail', models.EmailField(max_length=254, unique=True)),
                ('usuEstado', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('rolCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
