# Generated by Django 5.2.7 on 2025-11-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_create_default_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='rolNivel',
            field=models.IntegerField(choices=[(0, 'Nivel 0'),(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')], default=1),
        ),
        migrations.AlterField(
            model_name='role',
            name='rolNom',
            field=models.CharField(choices=[('GERENTE', 'Gerente'), ('CAJERO', 'Cajero'), ('VENDEDOR', 'Vendedor'), ('OPTOMETRA', 'Optometra'), ('SUPERVISOR', 'Supervisor'), ('LOGISTICA', 'Logística')], max_length=50),
        ),
    ]
