# Generated by Django 5.2.7 on 2025-11-03 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_role_rolnivel_alter_role_rolnom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usuContra',
        ),
    ]
