# Generated by Django 5.2.7 on 2025-11-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_user_usucontra'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usuContra',
            field=models.CharField(default='2025', max_length=128),
            preserve_default=False,
        ),
    ]
