# Generated by Django 5.2.7 on 2025-11-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_user_usucontra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usuContra',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
