# Generated by Django 5.2.7 on 2025-11-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_user_rolcod_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usuApell',
        ),
        migrations.AddField(
            model_name='user',
            name='usuNombreCom',
            field=models.CharField(max_length=60),
            preserve_default=False,
        ),
    ]
