# Generated by Django 5.2.7 on 2025-11-14 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_alter_branch_sucurestado'),
        ('User', '0008_remove_user_usuapell_user_usunombrecom'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sucurCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Branch.branch', verbose_name='Sucursal Asignada'),
        ),
    ]
