# Generated by Django 5.2.7 on 2025-11-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_user_sucurcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='rolNivel',
            field=models.IntegerField(choices=[(0, 'Nivel 0'), (1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4')], default=1),
        ),
    ]
