# Generated by Django 5.2.7 on 2025-12-19 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_load_sample_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptometraUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optCargo', models.CharField(max_length=50)),
                ('optCMP', models.CharField(max_length=20, unique=True)),
                ('optRNE', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='optometra', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
