# Generated by Django 5.2.7 on 2025-11-10 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('catproCod', models.AutoField(primary_key=True, serialize=False)),
                ('catproNom', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
