# Generated by Django 5.2.7 on 2025-11-10 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0003_alter_branch_sucurestado'),
        ('inventory', '0001_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['catproNom'], 'verbose_name': 'Categoría de Producto', 'verbose_name_plural': 'Categorías de Productos'},
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='product_category',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prodCod', models.AutoField(primary_key=True, serialize=False)),
                ('prodDescr', models.TextField(help_text='Descripción que aparecerá en la boleta/factura', verbose_name='Descripción')),
                ('prodMarca', models.CharField(max_length=100, verbose_name='Marca')),
                ('prodMate', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('prodPublico', models.CharField(choices=[('ADULTO', 'Adulto'), ('JOVEN', 'Joven'), ('NIÑO', 'Niño'), ('BEBE', 'Bebé'), ('UNISEX', 'Unisex'), ('TODOS', 'Todos')], default='TODOS', help_text='¿A qué público está dirigido? (Adulto, Joven, Niño, etc.)', max_length=20, verbose_name='Público Objetivo')),
                ('prodTipoAfecIGV', models.CharField(choices=[('10', 'Gravado - Operación Onerosa'), ('20', 'Exonerado - Operación Onerosa'), ('30', 'Inafecto - Operación Onerosa'), ('40', 'Exportación')], default='10', help_text='Código SUNAT: 10=Gravado, 20=Exonerado, 30=Inafecto', max_length=2, verbose_name='Tipo Afectación IGV')),
                ('prodCostoInv', models.DecimalField(decimal_places=2, help_text='Precio de compra del producto', max_digits=10, verbose_name='Costo de Inventario')),
                ('prodValorUni', models.DecimalField(decimal_places=2, help_text='Precio de venta SIN IGV (Base imponible)', max_digits=10, verbose_name='Valor Unitario')),
                ('prodStock', models.IntegerField(default=0, verbose_name='Stock Disponible')),
                ('prodUnidadMedi', models.CharField(choices=[('NIU', 'NIU - Unidad (bienes)'), ('ZZ', 'ZZ - Unidad (servicios)'), ('BX', 'BX - Caja'), ('PK', 'PK - Paquete'), ('SET', 'SET - Juego'), ('PR', 'PR - Par'), ('DZN', 'DZN - Docena')], default='NIU', help_text='Código SUNAT (Catálogo 03) - Aparece en boleta/factura', max_length=10, verbose_name='Unidad de Medida')),
                ('prodEstado', models.CharField(choices=[('Active', 'Activo'), ('Inactive', 'Inactivo')], default='Active', max_length=10, verbose_name='Estado')),
                ('catproCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.productcategory', verbose_name='Categoria')),
                ('provCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suppliers.supplier', verbose_name='Proveedor')),
                ('sucurCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Branch.branch', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'product',
                'ordering': ['prodMarca', 'prodDescr'],
            },
        ),
        migrations.CreateModel(
            name='BranchInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invStock', models.IntegerField(default=0, help_text='Cantidad disponible en esta sucursal', verbose_name='Stock en Sucursal')),
                ('invStockMin', models.IntegerField(default=5, help_text='Cantidad mínima antes de generar alerta', verbose_name='Stock Mínimo')),
                ('sucurCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Branch.branch', verbose_name='Sucursal')),
                ('prodCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Inventario de Sucursal',
                'verbose_name_plural': 'Inventarios de Sucursales',
                'db_table': 'branch_inventory',
                'ordering': ['sucurCod', 'prodCod'],
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('catproCod', 'provCod', 'prodDescr'), name='unique_product_per_category_supplier'),
        ),
        migrations.AddConstraint(
            model_name='branchinventory',
            constraint=models.UniqueConstraint(fields=('sucurCod', 'prodCod'), name='unique_inventory_per_branch_product'),
        ),
    ]
