# Generated by Django 5.2.7 on 2025-11-13 23:53

from django.db import migrations

def create_default_categories(apps, schema_editor):
    ProductCategory = apps.get_model('inventory', 'ProductCategory')

    default_categories = [
        "Accesorios",
        "Monturas",
        "Lunas",
        "Estuches",
        "Productos de Limpieza",
    ]

    for name in default_categories:
        ProductCategory.objects.get_or_create(catproNom=name)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_categories),
    ]
