# Generated by Django 5.2.7 on 2025-11-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodBarcode',
            field=models.CharField(blank=True, help_text='Código de barras EAN-13 (13 dígitos)', max_length=13, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
