# Generated by Django 5.2.7 on 2025-11-14 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20251113_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sucurCod',
        ),
    ]
