# Generated by Django 5.2.7 on 2025-11-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_prodbarcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='catproNom',
            field=models.CharField(choices=[('LENTES', 'Lentes'), ('MONTURAS', 'Monturas'), ('CRISTALES', 'Cristales / Micas'), ('ACCESORIOS', 'Accesorios'), ('LIQUIDOS', 'Líquidos de Limpieza'), ('SOLUCIONES', 'Soluciones y Gotas'), ('ESTUCHES', 'Estuches'), ('OTROS', 'Otros')], max_length=100, unique=True, verbose_name='Categoría'),
        ),
    ]
