# Generated by Django 5.2.7 on 2025-11-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productcategory_catpronom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='catproNom',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
