# Generated by Django 5.2.7 on 2025-11-14 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_sucurcod'),
        ('inventory', '0005_alter_productcategory_catpronom'),
    ]

    operations = [
    ]
