# Generated by Django 5.2.7 on 2025-11-15 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_alter_branch_sucurestado'),
        ('inventory', '0006_merge_20251113_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prodStock',
        ),
        migrations.AddField(
            model_name='product',
            name='branchOwner',
            field=models.ForeignKey(blank=True, help_text='Solo para productos locales. Para productos globales debe ser NULL.', null=True, on_delete=django.db.models.deletion.PROTECT, to='Branch.branch', verbose_name='Sucursal Propietaria'),
        ),
        migrations.AddField(
            model_name='product',
            name='prodOrigin',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('LOCAL', 'Local')], default='GLOBAL', help_text='Global = creado por Gerente | Local = creado por Supervisor', max_length=10, verbose_name='Origen del Producto'),
        ),
    ]
