# Generated by Django 5.2.7 on 2025-11-12 18:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0003_alter_branch_sucurestado'),
        ('inventory', '0002_alter_productcategory_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo Venta')),
                ('cliCod', models.CharField(blank=True, max_length=20, verbose_name='Código Cliente')),
                ('cliNombreCom', models.CharField(default='CLIENTE GENÉRICO', max_length=200, verbose_name='Nombre Cliente')),
                ('cliDocTipo', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet Extranjería')], default='DNI', max_length=10, verbose_name='Tipo Documento')),
                ('cliDocNum', models.CharField(blank=True, max_length=11, verbose_name='Número Documento')),
                ('ventFecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Venta')),
                ('ventFechaEntrega', models.DateField(blank=True, null=True, verbose_name='Fecha de Entrega')),
                ('ventEstado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago Parcial'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado Venta')),
                ('ventEstadoRecoj', models.CharField(choices=[('PENDIENTE', 'Pendiente (en registro)'), ('LABORATORIO', 'En laboratorio'), ('LOCAL', 'Listo para recoger'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pedido')),
                ('ventSubTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal (sin IGV)')),
                ('ventIGV', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IGV Total')),
                ('ventTotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total a Pagar')),
                ('ventAdelanto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Adelanto/Pago Inicial')),
                ('ventSaldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Pendiente')),
                ('ventObservaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('ventAnulada', models.BooleanField(default=False, verbose_name='¿Anulada?')),
                ('ventMotivoAnulacion', models.TextField(blank=True, verbose_name='Motivo de Anulación')),
                ('sucurCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Branch.branch', verbose_name='Sucursal')),
                ('usuCod', models.ForeignKey(limit_choices_to={'roles__rolNom': 'VENDEDOR'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'venta',
                'ordering': ['-ventFecha'],
            },
        ),
        migrations.CreateModel(
            name='VentaDetalle',
            fields=[
                ('ventDetCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Detalle')),
                ('ventDetCantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('ventDetValorUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario (sin IGV)')),
                ('ventDetPrecioUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario (con IGV)')),
                ('ventDetSubtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal (sin IGV)')),
                ('ventDetIGV', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IGV')),
                ('ventDetTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total (con IGV)')),
                ('ventDetDescuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('ventDetAnulado', models.BooleanField(default=False, verbose_name='¿Anulado?')),
                ('ventDetDescripcion', models.CharField(max_length=500, verbose_name='Descripción Producto')),
                ('ventDetMarca', models.CharField(max_length=100, verbose_name='Marca')),
                ('prodCod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto')),
                ('ventCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'venta_detalle',
                'ordering': ['ventDetCod'],
            },
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['-ventFecha'], name='venta_ventFec_a85570_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['ventEstado'], name='venta_ventEst_8966cb_idx'),
        ),
    ]
