# Generated by Django 5.2.7 on 2025-11-13 04:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('comprCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Código')),
                ('comprTipo', models.CharField(choices=[('03', 'Boleta de Venta'), ('01', 'Factura'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito')], default='03', max_length=2, verbose_name='Tipo Comprobante')),
                ('comprSerie', models.CharField(default='B001', help_text='B001 para boletas, F001 para facturas', max_length=4, verbose_name='Serie')),
                ('comprCorrelativo', models.CharField(max_length=8, verbose_name='Correlativo')),
                ('comprFechaEmision', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Emisión')),
                ('comprRUCEmisor', models.CharField(max_length=11, verbose_name='RUC Emisor')),
                ('comprRazonSocialEmisor', models.CharField(max_length=200, verbose_name='Razón Social Emisor')),
                ('comprTipoDocReceptor', models.CharField(choices=[('1', 'DNI'), ('6', 'RUC'), ('0', 'Sin Documento')], default='1', max_length=1, verbose_name='Tipo Doc. Receptor')),
                ('comprNumDocReceptor', models.CharField(max_length=11, verbose_name='Número Doc. Receptor')),
                ('comprRazonSocialReceptor', models.CharField(max_length=200, verbose_name='Nombre/Razón Social Receptor')),
                ('comprMoneda', models.CharField(default='PEN', max_length=3, verbose_name='Moneda')),
                ('comprTotalGravadas', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Operaciones Gravadas')),
                ('comprTotalIGV', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total IGV')),
                ('comprTotalVenta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Venta')),
                ('comprEstadoSUNAT', models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('ENVIADO', 'Enviado a SUNAT'), ('ACEPTADO', 'Aceptado por SUNAT'), ('RECHAZADO', 'Rechazado por SUNAT'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20, verbose_name='Estado SUNAT')),
                ('comprMensajeSUNAT', models.TextField(blank=True, verbose_name='Mensaje SUNAT')),
                ('comprHash', models.CharField(blank=True, max_length=100, verbose_name='Hash')),
                ('comprXMLFirmado', models.TextField(blank=True, verbose_name='XML Firmado')),
                ('comprCDR', models.TextField(blank=True, verbose_name='CDR (Constancia de Recepción)')),
                ('ventCod', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sales.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'db_table': 'comprobante',
                'ordering': ['-comprFechaEmision'],
                'unique_together': {('comprSerie', 'comprCorrelativo')},
            },
        ),
        migrations.CreateModel(
            name='ComprobanteDetalle',
            fields=[
                ('comprDetCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Detalle')),
                ('prodCod', models.CharField(max_length=20, verbose_name='Código Producto')),
                ('comprDetNumLinea', models.IntegerField(verbose_name='Número de Línea')),
                ('comprDetDescripcion', models.CharField(max_length=500, verbose_name='Descripción Producto')),
                ('comprDetUnidadMedida', models.CharField(default='NIU', help_text='Catálogo 03 SUNAT: NIU=Unidad, ZZ=Servicio', max_length=10, verbose_name='Unidad de Medida')),
                ('comprDetCantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('comprDetValorUnitario', models.DecimalField(decimal_places=2, help_text='Precio sin IGV', max_digits=10, verbose_name='Valor Unitario')),
                ('comprDetValorVenta', models.DecimalField(decimal_places=2, help_text='Cantidad x Valor Unitario (sin IGV)', max_digits=10, verbose_name='Valor Venta')),
                ('comprDetTipoAfecIGV', models.CharField(default='10', help_text='10=Gravado, 20=Exonerado, 30=Inafecto', max_length=10, verbose_name='Tipo Afectación IGV')),
                ('comprDetIGV', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IGV')),
                ('comprDetPrecioUnitario', models.DecimalField(decimal_places=2, help_text='Precio con IGV incluido', max_digits=10, verbose_name='Precio Unitario')),
                ('comprDetTotalLinea', models.DecimalField(decimal_places=2, help_text='Valor Venta + IGV', max_digits=10, verbose_name='Total Línea')),
                ('comprDetDescAdicional', models.TextField(blank=True, verbose_name='Descripción Adicional')),
                ('comprCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.comprobante', verbose_name='Comprobante')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante',
                'verbose_name_plural': 'Detalles de Comprobantes',
                'db_table': 'comprobante_detalle',
                'ordering': ['comprDetNumLinea'],
                'unique_together': {('comprCod', 'comprDetNumLinea')},
            },
        ),
    ]
