# Generated by Django 5.2.7 on 2025-11-18 22:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_comprobante_comprobantedetalle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comprobante',
            options={'ordering': ['-comprFechaEmision']},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-ventFecha']},
        ),
        migrations.AlterModelOptions(
            name='ventadetalle',
            options={'ordering': ['ventDetCod']},
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprCDR',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprCod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprCorrelativo',
            field=models.IntegerField(verbose_name='Correlativo'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprEstadoSUNAT',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Envío'), ('ENVIADO', 'Enviado a SUNAT'), ('ACEPTADO', 'Aceptado por SUNAT'), ('RECHAZADO', 'Rechazado por SUNAT'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprFechaEmision',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprHash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprMensajeSUNAT',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprMoneda',
            field=models.CharField(default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprNumDocReceptor',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprRUCEmisor',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprRazonSocialEmisor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprRazonSocialReceptor',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprSerie',
            field=models.CharField(default='B001', help_text='B001 para boletas, F001 para facturas', max_length=4),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTipo',
            field=models.CharField(choices=[('03', 'Boleta de Venta'), ('01', 'Factura'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito')], default='03', max_length=2),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTipoDocReceptor',
            field=models.CharField(choices=[('1', 'DNI'), ('6', 'RUC'), ('-', 'Sin Documento')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTotalGravadas',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTotalIGV',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTotalVenta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprXMLFirmado',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliDocNum',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliDocTipo',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet Extranjería')], default='DNI', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliNombreCom',
            field=models.CharField(default='CLIENTE GENÉRICO', max_length=200),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuCod',
            field=models.ForeignKey(limit_choices_to={'roles__rolNom__in': ['VENDEDOR', 'CAJERO']}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventAdelanto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventAnulada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventEstado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Pago Parcial'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventEstadoRecoj',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente (en registro)'), ('LABORATORIO', 'En laboratorio'), ('LOCAL', 'Listo para recoger'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventFecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventFechaEntrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventIGV',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventMotivoAnulacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventObservaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventSaldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventSubTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventTotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetAnulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetDescripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetIGV',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetMarca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetPrecioUni',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetSubtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetTotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ventadetalle',
            name='ventDetValorUni',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='ComprobanteDetalle',
        ),
    ]
