# Generated by Django 5.2.7 on 2025-11-19 03:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_alter_branch_sucurestado'),
        ('sales', '0003_alter_comprobante_options_alter_venta_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='ventFormaPago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('MIXTO', 'Pago Mixto')], default='EFECTIVO', max_length=15, verbose_name='Forma de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ventReferenciaPago',
            field=models.CharField(blank=True, help_text='Número de operación, voucher, etc.', max_length=50, verbose_name='Referencia de Pago'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ventTarjetaTipo',
            field=models.CharField(blank=True, choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('', 'No Aplica')], max_length=10, verbose_name='Tipo de Tarjeta'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['ventFormaPago'], name='venta_ventFor_59346c_idx'),
        ),
    ]
