# Generated by Django 5.2.7 on 2025-11-19 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
        ('sales', '0004_venta_ventformapago_venta_ventreferenciapago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cajaAperCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.cash', verbose_name='Caja asociada'),
        ),
    ]
