# Generated by Django 5.2.7 on 2025-11-19 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_alter_cash_cajnom'),
        ('sales', '0005_venta_cajaapercod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cajaAperCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cash.cashopening', verbose_name='Caja asociada'),
        ),
    ]
