# Generated by Django 5.2.7 on 2025-11-21 16:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_product_created_at'),
        ('sales', '0006_alter_venta_cajaapercod'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteDetalle',
            fields=[
                ('comprDetCod', models.AutoField(primary_key=True, serialize=False, verbose_name='Código Detalle Comprobante')),
                ('comprDetDescripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('comprDetMarca', models.CharField(max_length=100, verbose_name='Marca')),
                ('comprDetCantidad', models.IntegerField(verbose_name='Cantidad')),
                ('comprDetValorUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Unitario')),
                ('comprDetPrecioUni', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('comprDetSubtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('comprDetIGV', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IGV')),
                ('comprDetDescuento', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento')),
                ('comprDetTotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('comprDetTipoIGV', models.CharField(choices=[('10', 'Gravado - Operación Onerosa'), ('20', 'Exonerado - Operación Onerosa'), ('30', 'Inafecto - Operación Onerosa'), ('40', 'Exportación'), ('31', 'Gratuita')], max_length=2, verbose_name='Tipo de Afectación IGV')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante',
                'verbose_name_plural': 'Detalles de Comprobante',
                'db_table': 'comprobante_detalle',
                'ordering': ['comprDetCod'],
            },
        ),
        migrations.RemoveIndex(
            model_name='venta',
            name='venta_ventFor_59346c_idx',
        ),
        migrations.AlterUniqueTogether(
            name='comprobante',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliCod',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='comprDireccionEmisor',
            field=models.CharField(default='SIN DIRECCION', max_length=255),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='comprDireccionReceptor',
            field=models.TextField(blank=True, verbose_name='Dirección Receptor'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='comprTotalExoneradas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='comprTotalInafectas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='venta',
            name='cliDireccion',
            field=models.CharField(blank=True, help_text='Obligatorio para facturas, opcional para boletas', max_length=200, verbose_name='Dirección del Cliente'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ventTotalExonerada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Exonerada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ventTotalGratuita',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Gratuita'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ventTotalGravada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Gravada'),
        ),
        migrations.AddField(
            model_name='venta',
            name='ventTotalInafecta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Inafecta'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprCod',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprEstadoSUNAT',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de envío'), ('ENVIADO', 'Enviado a SUNAT'), ('ACEPTADO', 'Aceptado por SUNAT'), ('OBSERVADO', 'Observado por SUNAT'), ('RECHAZADO', 'Rechazado por SUNAT'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprFechaEmision',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Emisión'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprMensajeSUNAT',
            field=models.TextField(blank=True, verbose_name='Mensaje SUNAT'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprMoneda',
            field=models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprNumDocReceptor',
            field=models.CharField(max_length=15, verbose_name='Número Documento Receptor'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprRUCEmisor',
            field=models.CharField(max_length=11, verbose_name='RUC Emisor'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprRazonSocialEmisor',
            field=models.CharField(max_length=200, verbose_name='Razón Social Emisor'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprRazonSocialReceptor',
            field=models.CharField(max_length=200, verbose_name='Razón Social Receptor'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprSerie',
            field=models.CharField(max_length=4, verbose_name='Serie'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTipo',
            field=models.CharField(choices=[('01', 'Factura'), ('03', 'Boleta de Venta'), ('07', 'Nota de Crédito'), ('08', 'Nota de Débito')], max_length=2, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTipoDocReceptor',
            field=models.CharField(choices=[('1', 'DNI'), ('6', 'RUC'), ('-', 'No Aplica')], max_length=1, verbose_name='Tipo Documento Receptor'),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTotalGravadas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTotalIGV',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='comprTotalVenta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='ventCod',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='sales.venta', verbose_name='Venta asociada'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliDocTipo',
            field=models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet Extranjería'), ('', 'No Especificado')], default='DNI', max_length=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventCod',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Código Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventEstadoRecoj',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('LABORATORIO', 'En laboratorio'), ('LISTO', 'Listo para recoger'), ('ENTREGADO', 'Entregado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='venta',
            name='ventReferenciaPago',
            field=models.CharField(blank=True, max_length=50, verbose_name='Referencia de Pago'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['comprSerie', 'comprCorrelativo'], name='comprobante_comprSe_85c5b8_idx'),
        ),
        migrations.AddIndex(
            model_name='comprobante',
            index=models.Index(fields=['comprEstadoSUNAT'], name='comprobante_comprEs_6f672e_idx'),
        ),
        migrations.AddField(
            model_name='comprobantedetalle',
            name='comprCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sales.comprobante', verbose_name='Comprobante'),
        ),
        migrations.AddField(
            model_name='comprobantedetalle',
            name='prodCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='comprCDR',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='comprHash',
        ),
        migrations.RemoveField(
            model_name='comprobante',
            name='comprXMLFirmado',
        ),
    ]
