# Generated by Django 5.2.7 on 2025-11-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_comprobantedetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='comprCodigoRespuesta',
            field=models.CharField(blank=True, max_length=10, verbose_name='Código de respuesta SUNAT'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='comprFechaEnvio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío a SUNAT'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='comprFechaRespuesta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha respuesta SUNAT'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='comprHash',
            field=models.CharField(blank=True, max_length=100, verbose_name='Hash del comprobante'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='comprNombreCDR',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre archivo CDR'),
        ),
    ]
