# Generated by Django 5.2.7 on 2025-11-04 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cli_dni', models.CharField(max_length=8, unique=True)),
                ('cli_nombre', models.CharField(max_length=100)),
                ('cli_direccion', models.CharField(max_length=200)),
                ('cli_telefono', models.CharField(max_length=9)),
                ('cli_email', models.EmailField(max_length=254, unique=True)),
                ('cli_ciudad', models.CharField(max_length=100)),
                ('cli_estado', models.CharField(default='Activo', max_length=10)),
            ],
        ),
    ]
