# Generated by Django 5.2.7 on 2025-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_direccion',
            new_name='cliDirec',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_email',
            new_name='cliEmail',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_ciudad',
            new_name='cliNomComp',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cli_telefono',
            new_name='cliTelef',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cli_dni',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cli_estado',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cli_nombre',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliCod',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliNumDoc',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliRazSocial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliTipoDoc',
            field=models.CharField(default='DNI', max_length=10),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sucurCod',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
