# Generated by Django 5.2.8 on 2025-11-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_rename_cli_direccion_cliente_clidirec_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliNomComp',
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliApellido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliNombre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliTipoDoc',
            field=models.CharField(choices=[('DNI', 'DNI'), ('CE', 'Carnet de extranjeria')], default='DNI', max_length=10),
        ),
    ]
