# Generated by Django 5.2.8 on 2025-11-21 16:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_alter_branch_sucurestado'),
        ('clients', '0003_remove_cliente_clinomcomp_cliente_cliapellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliFechaNac',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sucurCod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Branch.branch'),
        ),
    ]
