# Generated by Django 5.2.8 on 2025-11-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0004_alter_branch_sucurestado'),
        ('clients', '0004_cliente_clifechanac_alter_cliente_sucurcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sucurCod',
            field=models.ForeignKey(blank=True, db_column='sucurCod', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='Branch.branch', verbose_name='Sucursal'),
        ),
    ]
