# Generated by Django 5.2.7 on 2025-12-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_load_sample_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cliFechaNac',
            field=models.DateField(blank=True, null=True),
        ),
    ]
