# Generated by Django 5.2.7 on 2025-12-19 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0005_load_sample_branches'),
        ('clients', '0005_cliente_clifechanac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sucurCod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Branch.branch', verbose_name='Sucursal'),
        ),
    ]
