# Generated by Django 5.2.7 on 2025-12-19 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_alter_cliente_sucurcod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='sucurCod',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
