# Generated by Django 5.2.7 on 2025-11-03 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('sucurCod', models.AutoField(primary_key=True, serialize=False)),
                ('sucurNom', models.CharField(max_length=100)),
                ('sucurCiu', models.CharField(max_length=100)),
                ('sucurDir', models.CharField(max_length=200)),
                ('sucurTel', models.CharField(max_length=20)),
                ('sucurEstado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BranchUser',
            fields=[
                ('sucUsuCod', models.AutoField(primary_key=True, serialize=False)),
                ('sucUsuFechAsig', models.DateField()),
                ('sucurCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.branch')),
                ('usuCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
    ]
