# Generated by Django 5.2.7 on 2025-11-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='sucurDep',
            field=models.CharField(choices=[('AMAZONAS', 'Amazonas'), ('ANCASH', 'Áncash'), ('APURIMAC', 'Apurímac'), ('AREQUIPA', 'Arequipa'), ('AYACUCHO', 'Ayacucho'), ('CAJAMARCA', 'Cajamarca'), ('CALLAO', 'Callao'), ('CUSCO', 'Cusco'), ('HUANCAVELICA', 'Huancavelica'), ('HUANUCO', 'Huánuco'), ('ICA', 'Ica'), ('JUNIN', 'Junín'), ('LA_LIBERTAD', 'La Libertad'), ('LAMBAYEQUE', 'Lambayeque'), ('LIMA', 'Lima'), ('LORETO', 'Loreto'), ('MADRE_DE_DIOS', 'Madre de Dios'), ('MOQUEGUA', 'Moquegua'), ('PASCO', 'Pasco'), ('PIURA', 'Piura'), ('PUNO', 'Puno'), ('SAN_MARTIN', 'San Martín'), ('TACNA', 'Tacna'), ('TUMBES', 'Tumbes'), ('UCAYALI', 'Ucayali')], default='Arequipa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='sucurDis',
            field=models.CharField(default='Arequipa', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branch',
            name='sucurCiu',
            field=models.CharField(max_length=30),
        ),
    ]
