# Generated by Django 5.2.7 on 2025-11-14 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0003_alter_branch_sucurestado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='sucurEstado',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10),
        ),
    ]
