# Generated by Django 5.2.7 on 2025-12-19 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0005_load_sample_branches'),
        ('clients', '0004_load_sample_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recCod', models.AutoField(primary_key=True, serialize=False)),
                ('recFecha', models.DateField(auto_now_add=True)),
                ('recTipoLente', models.CharField(max_length=100)),
                ('recEstado', models.CharField(default='Activo', max_length=50)),
                ('recObservaciones', models.TextField(blank=True, null=True)),
                ('dpGeneral', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_od_esf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_od_cil', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_od_eje', models.IntegerField(blank=True, null=True)),
                ('lejos_od_avcc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lejos_od_dip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_oi_esf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_oi_cil', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('lejos_oi_eje', models.IntegerField(blank=True, null=True)),
                ('lejos_oi_avcc', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('lejos_oi_dip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cerca_od_esf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cerca_od_cil', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cerca_od_eje', models.IntegerField(blank=True, null=True)),
                ('cerca_od_add', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('cerca_oi_esf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cerca_oi_cil', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cerca_oi_eje', models.IntegerField(blank=True, null=True)),
                ('cerca_oi_add', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('diagnostico', models.JSONField(blank=True, default=list)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='clients.cliente')),
                ('optometra', models.ForeignKey(limit_choices_to={'roles__rolNom': 'OPTOMETRA'}, on_delete=django.db.models.deletion.PROTECT, related_name='recipes_realizadas', to=settings.AUTH_USER_MODEL)),
                ('sucurCod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Branch.branch')),
            ],
        ),
    ]
