# Generated by Django 5.2.7 on 2025-11-02 15:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('prov_cod', models.AutoField(primary_key=True, serialize=False, verbose_name='Supplier Code')),
                ('prov_ruc', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='RUC must be exactly 11 digits', regex='^\\d{11}$')], verbose_name='RUC')),
                ('prov_raz_social', models.CharField(max_length=255, verbose_name='Razon Social')),
                ('prov_direc', models.TextField(verbose_name='Address')),
                ('prov_tele', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Phone must be exactly 9 digits', regex='^\\d{9}$')], verbose_name='Phone')),
                ('prov_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email')),
                ('prov_ciu', models.CharField(max_length=100, verbose_name='City')),
                ('prov_estado', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=10, verbose_name='Status')),
            ],
        ),
    ]
