# Generated by Django 5.2.7 on 2025-11-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='prov_ciu',
            new_name='provCiu',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='prov_cod',
            new_name='provCod',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='prov_direc',
            new_name='provDirec',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='prov_email',
            new_name='provEmail',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='prov_estado',
            new_name='provEstado',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='prov_raz_social',
            new_name='provRazSocial',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='prov_ruc',
            new_name='provRuc',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='prov_tele',
            new_name='provTele',
        ),
    ]
