# Generated by Django 5.2.7 on 2025-11-19 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Branch', '0004_alter_branch_sucurestado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('cajCod', models.AutoField(primary_key=True, serialize=False)),
                ('cajNom', models.CharField(max_length=30, unique=True)),
                ('cajDes', models.CharField(blank=True, null=True)),
                ('cajEstado', models.CharField(choices=[('ACTIVO', 'Activo'), ('DESACTIVADO', 'Desactivado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO')),
                ('sucurCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Branch.branch')),
                ('usuCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CashOpening',
            fields=[
                ('cajaAperCod', models.AutoField(primary_key=True, serialize=False)),
                ('cajaApertuFechHora', models.DateTimeField(auto_now_add=True)),
                ('cajaAperMontInicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cajaAperFechaHorCierre', models.DateTimeField(blank=True, null=True)),
                ('cajaAperMontCierre', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cajaAperMontEsperado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cajaAperDiferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cajaAperEstado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada')], default='ABIERTA', max_length=10)),
                ('cajaAperObservacio', models.TextField(blank=True, null=True)),
                ('cajCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aperturas', to='cash.cash')),
                ('usuCod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Apertura de Caja',
                'verbose_name_plural': 'Aperturas de Caja',
            },
        ),
    ]
