# Generated by Django 5.2.7 on 2025-11-19 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash',
            name='cajNom',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
